// webapp/src/pages/InterestSelection.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { analyticsService } from '../services/analyticsService.js'
import { schoolService } from '../services/schoolService.js'

const route = useRoute()
const router = useRouter()
const tourAppointmentId = ref(null)
const schoolId = ref(null)

// Placeholder interests (will be extracted from mobile app later)
const interests = ref([
  { id: "science_and_labs", name: "🔬 Science & Labs" },
  { id: "engineering", name: "⚙️ Engineering" },
  { id: "business", name: "💼 Business" },
  { id: "computing", name: "💻 Computing" },
  { id: "arts_and_theater", name: "🎭 Arts & Theater" },
  { id: "music", name: "🎶 Music" },
  { id: "athletics", name: "🏟️ Athletics" },
  { id: "recreation_and_fitness", name: "🏋️ Recreation & Fitness" },
  { id: "dorm-life", name: "🛏️ Dorm Life" },
  { id: "campus-dining", name: "🍔 Campus Dining" },
  { id: "clubs", name: "🧑‍🤝‍🧑 Student Clubs" },
  { id: "library_and_study-spaces", name: "📚 Library & Study Spaces" },
  { id: "nature_and_outdoor-spots", name: "🌳 Nature & Outdoor Spots" },
  { id: "history_and_landmarks", name: "🏰 History & Landmarks" },
  { id: "health_and_wellness", name: "🩺 Health & Wellness" },
  { id: "faith_and_spirituality", name: "✝️ Faith & Spirituality" },
  { id: "community", name: "🤝 Community" },
  { id: "career-services", name: "🎓 Career Services" }
])

const selectedInterests = ref([])
const isGenerating = ref(false)

// Get tour appointment ID and school ID from query parameters and storage
onMounted(() => {
  tourAppointmentId.value = route.query.tour_appointment_id || null
  schoolId.value = schoolService.getSelectedSchool()
  
  console.log('Tour Appointment ID:', tourAppointmentId.value)
  console.log('School ID:', schoolId.value)
})

// Toggle interest selection
const toggleInterest = (interestId) => {
  if (selectedInterests.value.includes(interestId)) {
    selectedInterests.value = selectedInterests.value.filter(id => id !== interestId)
  } else {
    selectedInterests.value.push(interestId)
  }
}

// Generate tour (placeholder)
const generateTour = async () => {
  isGenerating.value = true
  
  try {
    // Export analytics for interest selection
    if (schoolId.value && selectedInterests.value.length > 0) {
      console.log('Exporting interest analytics:', {
        schoolId: schoolId.value,
        interests: selectedInterests.value,
        tourAppointmentId: tourAppointmentId.value
      })
      
      const analyticsResult = await analyticsService.exportInterestsChosen(
        schoolId.value,
        selectedInterests.value,
        tourAppointmentId.value
      )
      
      if (!analyticsResult.success) {
        console.warn('Failed to export analytics:', analyticsResult.error)
        // Continue with tour generation even if analytics fails
      }
    }
    
    // Navigate to confirmation page with tour details
    const queryParams = {
      interests: selectedInterests.value.join(',')
    }
    
    if (tourAppointmentId.value) {
      queryParams.tour_appointment_id = tourAppointmentId.value
    }
    
    await router.push({
      name: 'TourConfirmation',
      query: queryParams
    })
    
  } catch (error) {
    console.error('Error generating tour:', error)
    alert('Error generating tour. Please try again.')
  } finally {
    isGenerating.value = false
  }
}

// Show default tour
const showDefaultTour = () => {
  generateTour()
}
</script>

<template>
  <div class="max-w-4xl mx-auto">
    <!-- Hero Section -->
    <div class="text-center mb-12">
      <h1 class="text-4xl md:text-6xl font-bold text-white mb-6">
        Discover Your Campus
      </h1>
      <p class="text-xl text-gray-300 mb-8">
        Select your interests to create a personalized campus tour experience
      </p>
    </div>

    <!-- Interest Selection -->
    <div class="bg-gray-800 rounded-lg shadow-lg border border-gray-700 p-4 sm:p-8 mb-8">
      <h2 class="text-2xl font-bold text-white mb-6 text-center">
        What interests you most?
      </h2>
      
      <!-- Interest Tags -->
      <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 mb-8">
        <button
          v-for="interest in interests"
          :key="interest.id"
          @click="toggleInterest(interest.id)"
          :class="[
            'p-2 sm:p-4 rounded-lg border-2 transition-all duration-200 text-left',
            selectedInterests.includes(interest.id)
              ? 'bg-blue-600 border-blue-500 text-white transform scale-105'
              : 'bg-gray-700 border-gray-600 text-gray-300 hover:border-gray-500 hover:bg-gray-600'
          ]"
        >
          <span class="text-sm font-medium">{{ interest.name }}</span>
        </button>
      </div>

      <!-- Action Buttons -->
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <button
          @click="generateTour"
          :disabled="selectedInterests.length === 0 || isGenerating"
          :class="[
            'px-8 py-3 rounded-lg font-medium transition-all duration-200',
            selectedInterests.length === 0 || isGenerating
              ? 'bg-gray-600 text-gray-400 cursor-not-allowed'
              : 'bg-blue-600 text-white hover:bg-blue-700 transform hover:scale-105'
          ]"
        >
          <span v-if="isGenerating" class="flex items-center justify-center">
            <svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            Generating Tour...
          </span>
          <span v-else>Submit Interests</span>
        </button>
        
        <button
          @click="showDefaultTour"
          :disabled="isGenerating"
          class="px-8 py-3 rounded-lg font-medium bg-gray-700 text-gray-300 hover:bg-gray-600 transition-all duration-200"
        >
          Skip Interest Selection
        </button>
      </div>

      <!-- Selection Count -->
      <div class="text-center mt-6">
        <p class="text-gray-400">
          {{ selectedInterests.length }} interest{{ selectedInterests.length !== 1 ? 's' : '' }} selected
        </p>
      </div>
    </div>

  </div>
</template>

<style scoped>
/* Additional styles if needed */
</style>

// mobile/app/interest-selection.tsx
import { useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import React, { useState, useEffect } from 'react';
import { 
  ScrollView, 
  StyleSheet, 
  Text, 
  TouchableOpacity, 
  View 
} from 'react-native';
import { 
  analyticsService, 
  schoolService, 
  tourGroupSelectionService 
} from '@/services/supabase';

const interests = [
  { id: "science_and_labs", name: "🔬 Science & Labs" },
  { id: "engineering", name: "⚙️ Engineering" },
  { id: "business", name: "💼 Business" },
  { id: "computing", name: "💻 Computing" },
  { id: "arts_and_theater", name: "🎭 Arts & Theater" },
  { id: "music", name: "🎶 Music" },
  { id: "athletics", name: "🏟️ Athletics" },
  { id: "recreation_and_fitness", name: "🏋️ Recreation & Fitness" },
  { id: "dorm-life", name: "🛏️ Dorm Life" },
  { id: "campus-dining", name: "🍔 Campus Dining" },
  { id: "clubs", name: "🧑‍🤝‍🧑 Student Clubs" },
  { id: "library_and_study-spaces", name: "📚 Library & Study Spaces" },
  { id: "nature_and_outdoor-spots", name: "🌳 Nature & Outdoor Spots" },
  { id: "history_and_landmarks", name: "🏰 History & Landmarks" },
  { id: "health_and_wellness", name: "🩺 Health & Wellness" },
  { id: "faith_and_spirituality", name: "✝️ Faith & Spirituality" },
  { id: "community", name: "🤝 Community" },
  { id: "career-services", name: "🎓 Career Services" }
];

export default function InterestSelectionScreen() {
  const router = useRouter();
  const [selectedInterests, setSelectedInterests] = useState<string[]>([]);
  const [schoolId, setSchoolId] = useState<string | null>(null);
  const [tourAppointmentId, setTourAppointmentId] = useState<string | null>(null);

  useEffect(() => {
    // Get school ID and tour appointment ID when component mounts
    const loadData = async () => {
      const selectedSchoolId = await schoolService.getSelectedSchool();
      const selectedTourGroupId = await tourGroupSelectionService.getSelectedTourGroup();
      
      setSchoolId(selectedSchoolId);
      setTourAppointmentId(selectedTourGroupId);
      
      console.log('School ID:', selectedSchoolId);
      console.log('Tour Appointment ID:', selectedTourGroupId);
    };
    
    loadData();
  }, []);

  const toggleInterest = (interestId: string) => {
    if (selectedInterests.includes(interestId)) {
      setSelectedInterests(selectedInterests.filter(id => id !== interestId));
    } else {
      setSelectedInterests([...selectedInterests, interestId]);
    }
  };

  const handleContinue = async () => {
    // Export analytics for interest selection if we have school data
    if (schoolId) {
      console.log('Exporting interest analytics:', {
        schoolId,
        interests: selectedInterests,
        tourAppointmentId
      });
      
      try {
        const analyticsResult = await analyticsService.exportInterestsChosen(
          schoolId,
          selectedInterests,
          tourAppointmentId
        );
        
        if (!analyticsResult.success) {
          console.warn('Failed to export analytics:', analyticsResult.error);
          // Continue with navigation even if analytics fails
        }
      } catch (error) {
        console.error('Error exporting analytics:', error);
        // Continue with navigation even if analytics fails
      }
    }
    
    // For ambassador-led tours, proceed to the map screen
    router.push('/(tabs)/map');
  };

  const handleBack = () => {
    router.back();
  };

  return (
    <View style={styles.container}>
      <StatusBar style="light" />
      
      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={handleBack}>
          <Text style={styles.backButtonText}>← Back</Text>
        </TouchableOpacity>
      </View>

      <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
        {/* Title Section */}
        <View style={styles.titleSection}>
          <Text style={styles.title}>Discover Your Campus</Text>
          <Text style={styles.subtitle}>
            Select your interests to personalize your tour experience
          </Text>
        </View>

        {/* Interest Grid */}
        <View style={styles.interestGrid}>
          {interests.map((interest) => (
            <TouchableOpacity
              key={interest.id}
              style={[
                styles.interestCard,
                selectedInterests.includes(interest.id) && styles.selectedInterestCard
              ]}
              onPress={() => toggleInterest(interest.id)}
            >
              <Text style={[
                styles.interestText,
                selectedInterests.includes(interest.id) && styles.selectedInterestText
              ]}>
                {interest.name}
              </Text>
              {selectedInterests.includes(interest.id) && (
                <View style={styles.selectedIndicator}>
                  <Text style={styles.checkmark}>✓</Text>
                </View>
              )}
            </TouchableOpacity>
          ))}
        </View>

        {/* Selected Count */}
        <View style={styles.selectionInfo}>
          <Text style={styles.selectionText}>
            {selectedInterests.length} interest{selectedInterests.length !== 1 ? 's' : ''} selected
          </Text>
        </View>

        {/* Action Section */}
        <View style={styles.actionSection}>
          <TouchableOpacity
            style={styles.continueButton}
            onPress={handleContinue}
          >
            <Text style={styles.continueButtonText}>
              {selectedInterests.length > 0 ? 'Continue with Selected Interests' : 'Continue with Default Tour'}
            </Text>
          </TouchableOpacity>
          
          <Text style={styles.helpText}>
            Your selected interests will help customize your tour experience. You can always explore other areas during the tour.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#282828',
  },
  header: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  backButton: {
    alignSelf: 'flex-start',
  },
  backButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  titleSection: {
    alignItems: 'center',
    marginBottom: 30,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 18,
    color: '#ccc',
    textAlign: 'center',
    lineHeight: 24,
  },
  interestGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  interestCard: {
    width: '48%',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    position: 'relative',
    minHeight: 60,
    justifyContent: 'center',
  },
  selectedInterestCard: {
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderColor: '#3B82F6',
  },
  interestText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    paddingRight: 20,
  },
  selectedInterestText: {
    fontWeight: '600',
  },
  selectedIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmark: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  selectionInfo: {
    alignItems: 'center',
    marginBottom: 30,
  },
  selectionText: {
    color: '#ccc',
    fontSize: 16,
    fontWeight: '500',
  },
  actionSection: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 20,
    marginBottom: 40,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  continueButton: {
    backgroundColor: '#3B82F6',
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 16,
  },
  continueButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  helpText: {
    color: '#ccc',
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
  },
});
